### ISSUE TITLE
    assert PointNavDatasetV1.check_config_paths_exist(config) AssertionError

### ISSUE THREAD

**Issue by Derry-Xing** [devendrachaplot/Neural-SLAM#55]
Hi, where can I find the tasks/pointnav_gibson.yaml ?

**Comment by devendrachaplot** [comment]
Config files are obtained from habitat-api repository:
https://github.com/devendrachaplot/habitat-api/blob/8ac1b16aa0554b10748a925f8a937954c77c1563/configs/tasks/pointnav_gibson.yaml

This error occurs usually due to missing dataset setup, check the instructions here:
https://github.com/devendrachaplot/Neural-SLAM#setup
